export const productValues = {
  title_en: "",
  title_ar: "",
  description_en: "",
  description_ar: "",
  priceBeforeDiscount: 1,
  quantity: 0,
  images: [],
  paymentType: "",
  keywords: [],
  category: [],
  subCategory: [],
  weight: 1,
  qualities: [],
  attributes: [],
  title_meta: "",
  desc_meta: "",
  link: "",
  title: "",
  message: "",
  subSubCategory: [],
  cities: [],
  neighborhoods: [],
};

export const productQualityValues = {
  key_en: "",
  key_ar: "",
  values: [],
};
